### ISSUE TITLE
implementing this into my website.

### ISSUE THREAD

**Issue by lilplayer6k** [Maadhav/youtube-downloader-API#4] opened 2021-02-22 17:18 UTC
Hello there dear Maadhav, i have downloaded the .zip file for the code then unzipped it and inserted the file as shown here into my website but it wont fetch the youtube videos so can you please help me figure this issue out please? attached are two images, one is of the code and one of the website itself when i inserted the youtube link and pressed fetch and the last one is when i inserted the youtube link into your website and pressed fetch @Maadhav @Athlon1600 @codezi @volkirik @arjunae 
![image](https://user-images.githubusercontent.com/78946868/108744386-b99c5180-74ee-11eb-8c2d-ef3814fd92e9.png)
![image](https://user-images.githubusercontent.com/78946868/108744413-c15bf600-74ee-11eb-8b3f-723f42a2f39c.png)
![image](https://user-images.githubusercontent.com/78946868/108744568-ef413a80-74ee-11eb-9fa5-234705fbaeca.png)

**Comment by Maadhav** [comment] 2021-02-23 00:37
The third image you have attached shows that the video is being fetched, is the issue still there? @Joshii01

**Comment by lilplayer6k** [comment] 2021-02-23 00:53
the third image is from your website that you linked, not from my website @Maadhav

**Comment by Maadhav** [comment] 2021-02-23 02:12
For now I would suggest you to use the code from the link I have given, meanwhile I will try to fix the issue as soon as I get some free time on weekends.

**Comment by lilplayer6k** [comment] 2021-02-23 02:14
ok thanks! by the way do you happen to know what the issue may be?

**Comment by lilplayer6k** [comment] 2021-02-23 02:16
and also can you please let me know when the issue is fixed?

**Comment by Maadhav** [comment] 2021-02-23 02:31
The issue is, Youtube constantly changes its source code so that the yt-downloaders stop working. I would have to update my code in order for it work. Will close this issue as soon as I fix it l, hopefully soon.

**Comment by lilplayer6k** [comment] 2021-02-23 02:44
ok thanks!

**Comment by lilplayer6k** [comment] 2021-02-24 17:19
Hey @Maadhav I just checked your youtube downloader and it works for you so i updated mine yet it still wont work so can you help me out?

**Comment by Maadhav** [comment] 2021-02-25 01:10
I have updated the code now, please try it once more and let me know.

**Closed as completed** 2021-03-01 01:37 UTC
