### ISSUE TITLE
get empty array as a result

### ISSUE THREAD

**Issue by FashionCStar** [Maadhav/youtube-downloader-API#3] opened 2020-08-28 19:17 UTC
$yt = new YouTubeDownloader();

$links = $yt->getDownloadLinks("https://www.youtube.com/watch?v=LJzCYSdrHMI");

var_dump($links); exit;

I am getting `array(0) {}` as a result.

How can I get useful mp4 url from above url ?

**Comment by Maadhav** [comment] 2020-08-29 01:21
https://maadhav-ytdl.herokuapp.com/video_info.php?url=https://www.youtube.com/watch?v=LJzCYSdrHMI

This is giving me the whole list of download link available.
I personally implemented this by doing a GET Request on the url I sent above.
Do let me know if it works for you. Cheers

**Comment by FashionCStar** [comment] 2020-08-29 15:04
This is the result I got with below api request.
https://maadhav-ytdl.herokuapp.com/video_info.php?url=https://www.youtube.com/watch?v=LJzCYSdrHMI


Array ( [{ ____"links":__ { "url": "https:\/\/r1---sn-p5qs7nek.googlevideo.com\/videoplayback?expire] => 1598662497 [ei] => AVNJX9_OCY6Phgbf5LWIAg [ip] => 54.210.176.137 [id] => o-AAHIMcxFkGLl57_dJzfahYC6epVJhh7ardehBgDE7Vcq [itag] => 251 [source] => youtube [requiressl] => yes [mh] => Yk [mm] => 31,26 [mn] => sn-p5qs7nek,sn-vgqsknez [ms] => au,onr [mv] => m [mvi] => 1 [pl] => 16 [initcwndbps] => 1196250 [vprv] => 1 [mime] => audio/webm [gir] => yes [clen] => 7931620 [ratebypass] => yes [dur] => 572.461 [lmt] => 1540134504925120 [mt] => 1598640754 [fvip] => 1 [c] => WEB [txp] => 5411222 [sparams] => expire,ei,ip,id,itag,source,requiressl,vprv,mime,gir,clen,dur,lmt [sig] => AOq0QJ8wRQIhAJ3lU0lMwlctJY-9PFLGd3KhVY0inh-0iCRJ0Ms4iQtcAiAxPITUIXblExG_JzNK4IARLmi6SkJEUD2jzz-UNU3iqQ== [lsparams] => mh,mm,mn,ms,mv,mvi,pl,initcwndbps [lsig] => AG3C_xAwRAIgMFXfSswoM6SjvspYOngv3UzcUhypwDlpTFtOEnB9R-QCIDmsI-QcMXVKg3vpZzE0fbATRS1J6kK64osHGyXZ4jjH", "itag": 251, "format": "webm, audio" } ], "error": null } [aitags] => 133,134,135,136,160,242,243,244,247,278 [keepalive] => yes )

**Comment by FashionCStar** [comment] 2020-08-29 15:45
`https://r1---sn-p5qs7nek.googlevideo.com/videoplayback?expire=1598737370&ei=endKX9StDoa9hwaZ6paoCg&ip=54.85.38.58&id=o-AIyp6yoyjfjbhbRU4iORkF0u9-gt4bYSRs7Ww7-TE13q&itag=18&source=youtube&requiressl=yes&mh=Yk&mm=31%2C29&mn=sn-p5qs7nek%2Csn-p5qlsnsr&ms=au%2Crdu&mv=u&mvi=1&pl=19&vprv=1&mime=video%2Fmp4&gir=yes&clen=14637675&ratebypass=yes&dur=572.511&lmt=1540133923381368&mt=1598715244&fvip=1&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgUQpaJsNZkG7SZzP0MqetLmuRLyaykc4Aq0g3FfqIAOYCIG7Hqpj3-hFujp6eealTmAH5HZoUDJq967ObCXxJdeFL&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRgIhANMs7c_8RALiZW_tKEnK0PcMZZ3WSDuqeIrLkOxW17LPAiEA3iObm8CHx7b5M9wCDNlXDPqdl5AzZ4hbRkexEoo_7LA%3D`

I got this url, but when I try to download it using ffmpeg, I am getting 403 error.
`ffmpeg -ss 30 -t 3 -i https://r1---sn-p5qs7nek.googlevideo.com/videoplayback?expire=1598736453&ei=5HNKX7imN8OG8wSBj4fQBw&ip=54.85.38.58&id=o-AFZryB1AYK_nLlMw4GGRz19TEpJ_D3C1HXOZg1k1uX09&itag=18&source=youtube&requiressl=yes&mh=Yk&mm=31%2C26&mn=sn-p5qs7nek%2Csn-vgqsknez&ms=au%2Conr&mv=u&mvi=1&pl=19&vprv=1&mime=video%2Fmp4&gir=yes&clen=14637675&ratebypass=yes&dur=572.511&lmt=1540133923381368&mt=1598714394&fvip=1&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJeegdrjP2kAOAoYWcjXzryut_uRr3-xgjPDil3_UaGqAiB-zV9zgf4jrM1R7zQcVbru0A-Fs5Rek7nu8ZzVOeBCpw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIhALo6EH96tlsUzj2Og6jQ0ASwQreVwanl8IdJ1OeFoTtbAiB-OMkzLK2dQR3aXoDww2TSD-zACXaMW6LgUowy3QZk7w%3D%3D output.gif`

```
[https @ 0000022b0b16d280] HTTP error 403 Forbidden
https://r1---sn-p5qs7nek.googlevideo.com/videoplayback?expire=1598736453: Server returned 403 Forbidden (access denied)
```

Also, when I visit above url, I am getting below screen
![image](https://user-images.githubusercontent.com/39269334/91640641-b8c5af80-e9e4-11ea-8e9e-3d7b90426bea.png)

The play button is not enabled.

**Comment by Maadhav** [comment] 2020-08-29 16:03
I guess the issue is on ur side.
When I open any link from the array that is fetched by my GET Request I see the video playing just fine.
![image](https://user-images.githubusercontent.com/21285859/91640975-125ac800-ea3f-11ea-904a-0356b0ceed91.png)
Now the main thing to notice here is that the URLs get expired within a certain amount of time so you need to fetch the latest link each time.

**Comment by FashionCStar** [comment] 2020-08-29 16:15
Okay, Thanks
I tried with other pc and it works fine.

Another question
There are many urls returned from request.
How can I get the url of highest quality video in php?

Thanks

**Comment by FashionCStar** [comment] 2020-08-30 02:42
https://maadhav-ytdl.herokuapp.com/video_info.php?url=https://www.youtube.com/watch?v=LJzCYSdrHMI

I am getting this screen with above url.

![image](https://user-images.githubusercontent.com/39269334/91650066-7b8f0b00-ea40-11ea-84ec-6491486a5cb3.png)

How can I use it ?

**Comment by Maadhav** [comment] 2020-08-30 03:18
Thats because this month's Free dynos in Heroku are over. This website will
start running next month. Meanwhile u could start running this project in
ur own server.

**Comment by FashionCStar** [comment] 2020-08-30 03:42
should I clone your project and run it on my server ?

**Comment by Maadhav** [comment] 2020-08-30 03:44
Yes Sure

**Comment by Maadhav** [comment] 2020-08-30 05:23
Should I close the issue now?

**Closed as completed** 2020-08-30 10:51 UTC
